
const info = {
                lat:'Geographical coordinates of the location (latitude)',
                lon:'Geographical coordinates of the location (longitude)',
                timezone:'Timezone name for the requested location',
                timezone_offset :'Shift in seconds from UTC',
                current :'Current weather data API response',
                dt:'Current time',
                sunrise:'Sunrise time',
                sunset :'Sunset time',
                temp :'Temperature. Units - default: kelvin, metric: Celsius, imperial: Fahrenheit',
                feels_like :'Temperature. This temperature parameter accounts for the human perception of weather. Units – default: kelvin, metric: Celsius, imperial: Fahrenheit.',
                pressure:'Atmospheric pressure on the sea level, hPa',
                humidity :'Humidity, %',
                dew_point :'Atmospheric temperature (varying according to pressure and humidity) below which water droplets begin to condense and dew can form. Units – default: kelvin, metric: Celsius, imperial: Fahrenheit.',
                clouds :'Cloudiness, %',
                uvi :'Current UV index',
                visibility:'Average visibility, metres',
                wind_speed :'Wind speed. Wind speed. Units – default: metre/sec, metric: metre/sec, imperial: miles/hour. How to change units used',
                wind_gust :'Wind gust. Units – default: metre/sec, metric: metre/sec, imperial: miles/hour. How to change units used',
                wind_deg :'Wind direction, degrees (meteorological)',
                moonrise:'The time of when the moon rises for this day',
                moonset:'The time of when the moon sets for this day',
                moon_phase:"Moon phase. 0 and 1 are 'new moon', 0.25 is 'first quarter moon', 0.5 is 'full moon' and 0.75 is 'last quarter moon'. The periods in between are called 'waxing crescent', 'waxing gibous', 'waning gibous', and 'waning crescent', respectively.",
                pop:'Probability of precipitation',
                rain :'Precipitation volume, mm',
                precipitation: 'Precipitation volume, mm',
                id:"Weather condition id",
                main:"Group of weather parameters (Rain, Snow, Extreme etc.)",
                base:"Internal parameter",
                temp_min:"Minimum temperature at the moment. This is minimal currently observed temperature (within large megalopolises and urban areas). Unit Default: Kelvin, Metric: Celsius, Imperial: Fahrenheit.",
                temp_max:"Maximum temperature at the moment. This is maximal currently observed temperature (within large megalopolises and urban areas). Unit Default: Kelvin, Metric: Celsius, Imperial: Fahrenheit.",
                sea_level:"Atmospheric pressure on the sea level, hPa",
                grnd_level:"Atmospheric pressure on the ground level, hPa",
                speed:"Wind speed. Unit Default: meter/sec, Metric: meter/sec, Imperial: miles/hour.",
                deg:"Wind direction, degrees (meteorological)",
                gust:"Wind gust. Unit Default: meter/sec, Metric: meter/sec, Imperial: miles/hour",
                all:"Cloudiness, %",
                '1h':"Rain volume for the last 1 hour, mm",
                '3h':"Rain volume for the last 3 hours, mm",
                '1h':"Snow volume for the last 1 hour, mm",
                '3h':"Snow volume for the last 3 hours, mm",
                dt:"Time of data calculation",
                message:"Internal parameter",
                country:"Country code (GB, JP etc.)",
                name:"City name",
                coord:"Coordinates from the specified location (latitude, longitude)",
                aqi:'Air Quality Index. Possible values: 1, 2, 3, 4, 5. Where 1 = Good, 2 = Fair, 3 = Moderate, 4 = Poor, 5 = Very Poor.',
                no:'Сoncentration of NO (Nitrogen monoxide), μg/m3',
                no2:'Сoncentration of NO2 (Nitrogen dioxide), μg/m3',
                o3:'Сoncentration of O3 (Ozone), μg/m3',
                so2:'Сoncentration of SO2 (Sulphur dioxide), μg/m3',
                pm2_5:'Сoncentration of PM2.5 (Fine particles matter), μg/m3',
                pm10:'Сoncentration of PM10 (Coarse particulate matter), μg/m3',
                nh3:'Сoncentration of NH3 (Ammonia), μg/m3',
                name:"Name of the found location",
                lat:"Geographical coordinates of the found location (latitude)",
                lon:"Geographical coordinates of the found location (longitude)",
                country:"Country of the found location",
                state:"(where available) State of the found location",
                zip:"Specified zip/post code in the API request"
              }

export default info;
